services:
  web:
    build: ./HabitaBackend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./HabitaBackend:/usr/src/HabitaBackend
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
